apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pam-pod-cm1
  name: pam-pod-cm1
spec:
  containers:
  - image: nginx
    name: pam-pod-cm1
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /usr/share/nginx/html/index.html
      subPath: index.html
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: config-volume
    configMap:
      name: pam-cm-1
status: {}
