version: '3.0'

services:
  simple-client:
    build: SimpleClient
    image: wwupi/simple-client
    ports:
      - "8080:8080"
      - "9990:9990"

  add-server:
    build: AddServer
    image: wwupi/add-server
    ports:
      - "8081:8080"
      - "9991:9990"

  multiply-server:
    build: MultiplyServer
    image: wwupi/multiply-server
    ports:
      - "8082:8080"
      - "9992:9990"